---
#Only the host name or ip. Dont enter http or https or any other protocolo type
nsxtapi:
  site1:
    nsxtmgr1:
      host_addr: '10.29.13.120'
      host_port: 443
      con_type: https #Connection Type example values   http https
      verifycert: False
      auth_user: 'admin'
      auth_pwd: VMware1!vmware
      time_out: 60
      #auth_token: ''
      #client_cert: ''
      #client_key: ''
    nsxtmgr2:
      host_addr: 'site1-nsxtmgr2-ip-addr'
      host_port: 8082
      con_type: https #Connection Type example values   http https
      verifycert: False
      auth_user: 'admin'
      auth_pwd: VMWare1!
      time_out: 60
      #auth_token: ''
      #client_cert: ''
      #client_key: ''
    nsxtmgr3:
      host_addr: 'site1-nsxtmgr3-ip-addr'
      host_port: 8083
      con_type: https  #Connection Type example values   http https
      verifycert: False
      auth_user: 'admin'
      auth_pwd: VMWare1!
      time_out: 60
      #auth_token: ''
      #client_cert: ''
      #client_key: ''
#Only the host name or ip. Dont enter http or https or any other protocolo type
  site2:
    nsxtmgr1:
      host_addr: 'site2-nsxtmgr1-ip-addr'
      host_port: 443
      con_type: https #Connection Type example values   http https
      verifycert: False
      auth_user: 'admin'
      auth_pwd: VMware1!vmware
      time_out: 60
      #auth_token: ''
      #client_cert: ''
      #client_key: ''
    nsxtmgr2:
      host_addr: 'site2-nsxtmgr2-ip-addr'
      host_port: 8082
      con_type: https #Connection Type example values   http https
      verifycert: False
      auth_user: 'admin'
      auth_pwd: VMWare1!
      time_out: 60
      #auth_token: ''
      #client_cert: ''
      #client_key: ''
    nsxtmgr3:
      host_addr: 'site2-nsxtmgr3-ip-addr'
      host_port: 8083
      con_type: https  #Connection Type example values   http https
      verifycert: False
      auth_user: 'admin'
      auth_pwd: VMWare1!
      time_out: 60
      #auth_token: ''
      #client_cert: ''
      #client_key: ''